worker_processes    auto;

events
{
	worker_connections  1024;
}

http
{
	include	/etc/nginx/mime.types;
	default_type	app/octect-stream;
	sendfile	on;

	server
	{
		listen	443 ssl;
		listen	[::]:443 ssl;
		server_name	alehenri.42.fr;
		ssl_certificate	/etc/ssl/certs/nginx.crt;
		ssl_certificate_key	/etc/ssl/private/nginx.key;
		ssl_protocols	TLSv1.2 TLSv1.3;
		root	/var/www/html;
		index	index.php index.html;
		# main location: try to serve the file directly, fall to index.php; required by WP permalinks(pretty URLs) to work. 
		# $uri->exact requested path; $uri/ = treat it as a directory
		# /index.php?$args = fall back to WP router with query string
		location /
		{
			try_files	$uri $uri/ /index.php?$args;
		}
		# FastCGI: any requests ending in .php get forwarded to php-fpm;
		location ~ \.php$ 
		{
			try_files	$uri =404;
			fastcgi_pass	wordpress:9000;
			fastcgi_index	index.php;
			include			fastcgi_params;
			fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param	PATH_INFO $fastcgi_path_info;
		}
		# static file caching
		location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2)$
		{
			expires	30d; # tell browser to cache static assets for 30days
			log_not_found	off; # don't pollute logs with missing favicon.ico errors;
		}
	}
}